### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by mastef** [cyrilwanner/next-optimized-images#101] opened 2019-08-09 11:09 UTC
I was getting cryptic `Error: write EPIPE` errors. At first I thought it had to do with webpack config including url-loaders or file-loaders, but after spending a day on debugging that, I found out that that wasn't the issue. So I'm using `next-optimized-images` with `next-css`, and the build process was always breaking when going through the `style.css` file : 
```
./components/style.css
Error: write EPIPE

> Build error occurred
Error: > Build failed because of webpack errors
```
Which really sucks, as it could be one of a million things. Then I started debugging in all the different packages, and narrowed it down to `next-optimized-images`. This is how I managed to debug it :
`npm install inspect-loader` - [a little loader that lets](https://github.com/peerigon/inspect-loader) you inject any kind of callback before a loader handles a resource.

Then in `resource-queries.js` I've added 
```
const inspectOptions = {
                callback(inspect) {
                     console.log(inspect.context.resourcePath);
                }
            };
```
Adjusted every `loaders` array to include `inspect-loader` first. E.g. : 
```diff
-    loaders: ['file-loader'],
+    loaders: ['inspect-loader','file-loader'],
```
And finally added `inspect-loader` options to `loaderOptions` : 
```diff
  const loaderOptions = {
+   'inspect-loader': inspectOptions,
    'url-loader': getUrlLoaderOptions(nextConfig, isServer),
    'file-loader': getFileLoaderOptions(nextConfig, isServer),
    'lqip-loader': getLqipLoaderOptions(nextConfig, isServer),
    'responsive-loader': getResponsiveLoaderOptions(nextConfig, isServer, detectLoaders),
    'image-trace-loader': getImageTraceLoaderOptions(nextConfig),
  };
```

This way I was able to follow which file is being handled when webpack throws that error. Because debug flags didn't help me anywhere, as there doesn't seem to be extra console.log output for files being processed. 

Turns out jpeg files around 4-5MB were throwing this error for me. So maybe moz-jpeg or lqip has an issue with huge files. I wasn't able to narrow it down yet to which loader exactly fails.

If there was an easier way to debug this, please let me know. Just wrote here my journey to help others running into this frustrating issue.

I think it would of course also be nice to handle cli failures with a more meaningful error message.

**Comment by cyrilwanner** [comment] 2019-09-02 15:29
I'm sorry that you had to invest so much time into this issue. But thank you for the detailed feedback!
I'll also try to reproduce and narrow it down. But since this error comes from a webpack loader, I can't do much in this plugin, so I'll close this issue here. When I found out which webpack loader is failing, I'll create a issue in their repository for a better error message.

**Closed by cyrilwanner** 2019-09-02 15:29 UTC

**Comment by mastef** [comment] 2019-09-03 01:44
> But since this error comes from a webpack loader, I can't do much in this plugin, so I'll close this issue here.

Throwing relevant error messages would be good, because right now I basically had to "hack the core" of this npm plugin to get any meaningful errors.
